require("settings").setup()
require("plugins").setup()
require("completion").setup()
require("lsp-config").setup()
--require("lsp-null-ls").setup()
require("themes").setup()
require("mappings").setup()
